apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kub-poc-gateway-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kub-poc-gateway
    spec:
      containers:
      - name: kub-poc-gateway
        image: poc/kub-poc-product:v1.0
        ports:
        - containerPort: 8080