apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kub-poc-gateway-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kub-poc-gateway
    spec:
      containers:
      - name: kub-poc-gateway
        image: kub-poc-gateway:v1.1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: public-token
          mountPath: "/tmp/public-token"
          readOnly: true
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080
      volumes:
      - name: public-token
        secret:
          secretName: public-token