apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kub-poc-gateway-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kub-poc-gateway
    spec:
      containers:
      - name: kub-poc-gateway
        image: poc/kub-poc-gateway:v2.2
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080