apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kub-poc-product-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kub-poc-product
    spec:
      containers:
      - name: kub-poc-product
        image: poc/kub-poc-product:v1.2
        ports:
        - containerPort: 8080
        - containerPort: 8081
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080