platform: linux
image_resource:
  type: docker-image
  source:
    repository: lachlanevenson/k8s-kubectl
    tag: "latest"
run:
  path: sh
  args:
  - -exc
  - |
    kubectl config set-cluster local-cluster --server=http://ae04df29.ngrok.io
    kubectl config set-context local-context --cluster=local-cluster
    kubectl config use-context local-context
    kubectl cluster-info
    kubectl --namespace=k8s apply -f  git-poc-k8s/_manifests/gateway-deploy.yaml
