platform: linux
image_resource:
  type: docker-image
  source:
    repository: lachlanevenson/k8s-kubectl
    tag: "latest"
run:
  path: sh
  args:
  - -exc
  - |
    kubectl config set-credentials admin --username=admin --client-certificate={{client-certificate-data}} --client-key={{client-key-data}}
    kubectl config set-cluster kubernetes --server=https://heptio-ku-apiloadb-q15tabanakti-878813041.eu-central-1.elb.amazonaws.com
    kubectl config set-context admin@kubernetes --cluster=kubernetes --certificate-authority={{certificate-authority-data}}
    kubectl config use-context admin@kubernetes
    kubectl cluster-info
    kubectl get deployments
    kubectl apply -f git-poc-k8s/_manifests/gateway-deploy.yaml
