platform: linux
inputs:
- name: build-docker-poc-k8s
outputs:
- name: done
image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "latest"
run:
  path: bash
  args:
  - -exc
  - |
    kubectl config set-cluster test-cluster --server=http://192.168.99.100:30000 --api-version=v1
    kubectl --namespace=k8s apply -f _manifests/gateway-deploy.yaml
