platform: linux
image_resource:
  type: docker-image
  source:
    repository: lachlanevenson/k8s-kubectl
    tag: "latest"
run:
  path: kubectl config set-cluster test-cluster --server=http://192.168.99.100:30000 --api-version=v1 && kubectl --namespace=k8s apply -f _manifests/gateway-deploy.yaml
