platform: linux
image_resource:
  type: docker-image
  source:
    repository: lachlanevenson/k8s-kubectl
    tag: "latest"
run:
  path: sh
  args:
  - -exc
  - |
    echo {{client-certificate-data}} > /tmp/client-certificate-data
    echo {{client-key-data}} > /tmp/client-key-data
    kubectl config set-credentials admin --username=admin --client-certificate=/tmp/client-certificate-data --client-key=/tmp/client-key-data
    kubectl config set-cluster kubernetes --server=https://heptio-ku-apiloadb-q15tabanakti-878813041.eu-central-1.elb.amazonaws.com --certificate-authority=/tmp/client-certificate-data
    kubectl config set-context admin@kubernetes --cluster=kubernetes --user=admin
    kubectl config use-context admin@kubernetes
    kubectl cluster-info
    kubectl get deployments
    kubectl apply -f git-poc-k8s/_manifests/gateway-deploy.yaml
