platform: linux
image_resource:
  type: docker-image
  source:
    repository: lachlanevenson/k8s-kubectl
    tag: "latest"
run:
  path: sh
  args:
  - -exc
  - |
    kubectl config set-cluster test-cluster --server=http://ae04df29.ngrok.io:30000 --api-version=v1
    kubectl --namespace=k8s apply -f _manifests/gateway-deploy.yaml
