platform: linux
image_resource:
  type: docker-image
  source:
    repository: lachlanevenson/k8s-kubectl
    tag: "latest"

inputs:
  - name: git-poc-k8s
  - name: client-key-data
  - name: client-certificate-data

run:
  path: sh
  args:
  - -exc
  - |
    echo client-certificate-data > /tmp/client-certificate.pem
    echo client-key-data > /tmp/client-key.pem
    kubectl config set-credentials admin --username=admin --client-certificate=/tmp/client-certificate.pem --client-key=/tmp/client-key.pem
    kubectl config set-cluster kubernetes --server=https://heptio-ku-apiloadb-q15tabanakti-878813041.eu-central-1.elb.amazonaws.com --insecure-skip-tls-verify=true
    kubectl config set-context admin@kubernetes --cluster=kubernetes --user=admin
    kubectl config use-context admin@kubernetes
    kubectl cluster-info
    kubectl get deployments
    kubectl apply -f git-poc-k8s/_manifests/gateway-deploy.yaml
