platform: linux
inputs:
- name: continuous-deployment-on-kubernetes
outputs:
- name: deploy
image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "latest"
run:
  path: bash
  args:
  - -exc
  - |
    kubectl --namespace=k8s apply -f _manifests/gateway-deploy.yaml
