apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kub-poc-gateway-deploy
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kub-poc-gateway
    spec:
      containers:
      - name: kub-poc-gateway
        image: qover/kub-poc-gateway
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080