apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kub-poc-jobloss-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kub-poc-jobloss
    spec:
      containers:
      - name: kub-poc-jobloss
        image: k8s/kub-poc-jobloss:v1.1
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080