apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kub-poc-security-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kub-poc-security
    spec:
      containers:
      - name: kub-poc-security
        image: k8s/kub-poc-security:v<VERSION>
        volumeMounts:
        - name: admin-key
          mountPath: "/tmp/admin-key"
          readOnly: true
        - name: b2b-key
          mountPath: "/tmp/b2b-key"
          readOnly: true
        - name: internal-key
          mountPath: "/tmp/internal-key"
          readOnly: true
        ports:
        - containerPort: 8083
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080 
      volumes:
      - name: admin-key
        secret:
          secretName: admin-key
      - name: b2b-key
        secret:
          secretName: b2b-key
      - name: internal-key
        secret:
          secretName: internal-key