apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kub-poc-security-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kub-poc-security
    spec:
      containers:
      - name: kub-poc-security
        image: poc/kub-poc-security:v1.0
        ports:
        - containerPort: 8083