jobs:  
- name: build-docker-poc-k8s
  public: true
  serial: true
  plan:
  - get: git-poc-k8s
    trigger: true
  - put: docker-image
    params:
      build: git-poc-k8s/kub-poc-jobloss
- name: apply-secrets-poc-k8s
  public: true
  serial: true
  plan:
  - get: git-poc-k8s
    passed: [build-docker-poc-k8s]
    trigger: true
  - task: deploy
    file: git-poc-k8s/_manifests/concourse/tasks/jobloss-secret.yaml
    params:
      git-poc-k8s: git-poc-k8s
- name: apply-deployments-poc-k8s
  public: true
  serial: true
  plan:
  - get: git-poc-k8s
    passed: [apply-secrets-poc-k8s]
    trigger: true
  - task: deploy
    file: git-poc-k8s/_manifests/concourse/tasks/jobloss-deployment.yaml
    params:
      git-poc-k8s: git-poc-k8s
- name: apply-services-poc-k8s
  public: true
  serial: true
  plan:
  - get: git-poc-k8s
    passed: [apply-deployments-poc-k8s]
    trigger: true
  - task: deploy
    file: git-poc-k8s/_manifests/concourse/tasks/jobloss-service.yaml
    params:
      git-poc-k8s: git-poc-k8s

resources:  
- name: git-poc-k8s
  type: git
  source:
    uri: {{github-url}}
    branch: concourse

- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-jobloss-repository}}